version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - BASE_URL=https://resonance.collab-cloud.eu:8081
      - USERNAME=admin
      - PASSWORD=password
