name: Build and Push to GHCR

on:
  push:
    branches:
      - main
      - production
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Extract repository and branch name
      id: vars
      run: |
        REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')
        REPO_OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
        BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '[:upper:]' '[:lower:]')
        if [ "${BRANCH_NAME}" == "main" ]; then
          IMAGE_TAG="stage:latest"
        elif [ "${BRANCH_NAME}" == "production" ]; then
          IMAGE_TAG="production:latest"
        else
          IMAGE_TAG="production:${BRANCH_NAME}"
        fi
        echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
        echo "REPO_OWNER=${REPO_OWNER}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}-${{ env.IMAGE_TAG }}
